name: Pull Request Workflow for Unlocked Package Deployment - Devint
on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'force-app/main/default/**'

jobs:
  validate_pull_request:
    name: Validation of Pull Request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
        image: salesforce/cli:latest-full
    env:
      SOURCE_BRANCH: ${{ github.head_ref }}
      TARGET_BRANCH: ${{ github.base_ref }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Apex Test Classes
        id: find-test-classes
        run: |
          find cmd-loader/main/default/classes -name '*Test.cls' -type f | xargs -n 1 basename | sed 's/.cls//' > test_classes.txt

      - name: Dev Int Sandbox-Validation
        run: |
          TEST_CLASSES=$(cat test_classes.txt | tr '\n' ' ')
          echo ${{ secrets.AUTH_DEVINT }} | sf org login sfdx-url -s -u
          sf project deploy validate -d force-app/main/default -l RunSpecifiedTests -t $TEST_CLASSES --verbose -w 20

  code_coverage_report:
    name: Apex Code Coverage Report
    needs: validate_pull_request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
        image: salesforce/cli:latest-full
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authorization to DevHub & Create Scratch Org
        run: |
          echo ${{ secrets.AUTH_PROD }} | sf org login sfdx-url -d -u
          sf org create scratch -f config/project-scratch-def.json -a ci_scratch -y 1

      - name: Package Version Installation on Scratch Org
        run: |
          echo ${{ secrets.AUTH_PROD }} | sf org login sfdx-url -d -u
          sf package version create -x -p "MyFirstApplication" -w 60 --code-coverage
          new_version_id=$(grep -o "04t[[:alnum:]]\{15\}" sfdx-project.json | tail -n1)
          test $(sf package version report -p $new_version_id --json | jq .result.HasPassedCodeCoverageCheck) = 'true'
          sf package install -p $new_version_id -o ci_scratch -w 10 -b 10

      - name: Apex Code Coverage Report Generation
        run: |
          sf apex run test -c -r json -d ./tests/apex -o ci_scratch -w 20 > test.json
          coverage=$(jq .result.summary.orgWideCoverage test.json | grep -Eo "[[:digit:]]+")
          test $coverage -ge 75

      - name: Upload Apex Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: apex-code-coverage
          path: tests/apex/test-result-codecoverage.json
  
      - name: Delete scratch org
        if: always()
        run: sf org delete scratch -p -o ci_scratch
        
  sonar_scan:
    name: SonarQube Scan
    needs: code_coverage_report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Apex Code coverage Report
        uses: actions/download-artifact@v4
        with:
          name: apex-code-coverage
          path: tests/apex

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
